name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAI’s ChatGPT and creates a pull request.'
author: 'Brendan Tomlinson'

inputs:
  github_token:
    description: 'GitHub token to authenticate API requests'
    required: true
  openai_api_key:
    description: 'OpenAI API key for accessing ChatGPT'
    required: true
  repository:
    description: 'The full repo name (e.g. user/repo)'
    required: true
  issue_number:
    description: 'The issue number that triggered the action'
    required: true
  script_path:
    description: 'Path to the script file'
    required: true
  label:
    description: 'Label that triggers the action'
    required: true

outputs:
  pull_request_url:
    description: 'URL of the created pull request'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x ${{ inputs.script_path }}
      shell: bash

    - name: Run code generation script
      run: ${{ inputs.script_path }} "${{ inputs.github_token }}" "${{ inputs.repository }}" "${{ inputs.issue_number }}" "${{ inputs.openai_api_key }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        REPOSITORY: ${{ inputs.repository }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: autocoder-artifact
        path: autocoder-bot/

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: autocoder-artifact
        path: autocoder-artifact/

    - name: List Files
      run: ls -R ./autocoder-artifact
    
    - name: Commit Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "autocoder-bot"
        git add .
        git commit -m "Add generated code from ChatGPT"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        labels: "autocoder-bot"
        author: autocoder-bot <actions@github.com>
        title: "#${{ github.event.issue.number }}"
        branch: autocoder-branch-${{ inputs.issue.number }}
