version: '3'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=mydb
