name: Autocoder Bot

on:
  issues:
    types: [opened]

jobs:
  generate_code:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Install jq
        run: sudo apt-get install -y jq

      - name: 🧠 Run Autocoder script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          bash ./autocoder.sh "$GITHUB_TOKEN" "${{ github.repository }}" "${{ github.event.issue.number }}" "$OPENAI_API_KEY"

      - name: 📤 Commit generated code
        run: |
          git config user.name "autocoder[bot]"
          git config user.email "autocoder@users.noreply.github.com"
          git add autocoder-bot
          git commit -m "🤖 Generated code from issue #${{ github.event.issue.number }}" || echo "Nothing to commit"
          git push
