name: Autocoder Bot Workflow

env:
    GH_TOKEN: ${{ github.token }}

on:
  issues:
    types: [opened, reopened, labeled]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate_code:  # ← required name
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')  # ← required job-level condition
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --local user.name "autocoder-bot"
          git config --local user.email "actions@github.com"

      - name: Set permissions for script.sh  # ← required step name
        run: chmod +x ./scripts/script.sh    # ← required exact command

      - name: Run script.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY

      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: ./autocoder-bot

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: ./autocoder-artifact

      - name: List files in artifact
        run: ls -R ./autocoder-artifact

      - name: Commit Changes
        run: |
          git config --local user.name "autocoder-bot"
          git config --local user.email "actions@github.com"
          git add ./autocoder-artifact
          git commit -m "Add generated code from ChatGPT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          labels: "autocoder-bot"
          author: autocoder-bot <actions@github.com>
          title: "#${{ github.event.issue.number }}"
          branch: autocoder-branch-${{ github.event.issue.number }}
