name: Autocoder Bot Workflow

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate_code:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if 'autocoder-bot' label is missing
        run: |
          echo "Checking for 'autocoder-bot' label..."
          labels=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[] | .name')
          echo "Found labels: $labels"
          if echo "$labels" | grep -q 'autocoder-bot'; then
            echo "Label check passed."
          else
            echo "Label 'autocoder-bot' not found. Failing job."
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set permissions for script.sh
        run: chmod +x scripts/script.sh

      - name: Run script.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY

      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: ./autocoder-bot

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: ./autocoder-artifact

      - name: List files in artifact
        run: ls -R ./autocoder-artifact
